[phases.setup]
nixPkgs = ['...', 'chromium', 'glib', 'nss', 'nspr', 'atk', 'dbus', 'libdrm', 'gtk3']

[variables]
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
